# Generated by Django 5.1 on 2024-08-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('travel_document', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=255)),
                ('date_of_issue', models.DateField()),
                ('issuing_authority', models.CharField(max_length=255)),
                ('issuing_country', models.CharField(max_length=255)),
                ('domicile_place', models.CharField(max_length=255)),
                ('domicile_zip_code', models.CharField(max_length=20)),
                ('domicile_street', models.CharField(max_length=255)),
                ('domicile_country', models.CharField(max_length=255)),
                ('traveling_with_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('traveling_with_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('traveling_with_date_of_birth', models.DateField(blank=True, null=True)),
                ('total_guests', models.IntegerField()),
                ('date_of_arrival', models.DateField()),
                ('date_of_departure', models.DateField()),
                ('actual_departure', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
