# Generated by Django 5.1 on 2024-08-11 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_guestsheet_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestsheet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
